<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="kishorebaskaran" failures="1" tests="1" name="Logintests" time="17.207" errors="0" timestamp="2025-07-30T17:51:45 IST">
  <testcase classname="tests.Logintest" name="testvalidlogin" time="8.03">
    <failure type="java.lang.AssertionError" message="expected [Just a moment..] but found [nopStation | #1 eCommerce Solution Provider | Login]">
      <![CDATA[java.lang.AssertionError: expected [Just a moment..] but found [nopStation | #1 eCommerce Solution Provider | Login]
at tests.Logintest.testvalidlogin(Logintest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testvalidlogin -->
</testsuite> <!-- Logintests -->
